### ISSUE TITLE
Not working (I'm new)

### ISSUE THREAD

**Issue by NewYears1978** [Azzmurr/raft-mods#3]
First time Raft player, this mod doesn't appear to work. I put planks in my inventory and when using Hammer I can't build.

Am I missing something?

Tried 2 other mods and they work so I know I am loading the mods correct.

Maybe I misunderstood and it only works when you open a storage and then craft from there, not universal crafting from all storage when doing any form of crafting?

**Comment by Azzmurr** [comment]
Hi there. Sorry for the long reply.
My mod "Craft From Storage" allows you to craft things using ingredients that are in **open** storage inventory.
This means if you open any storage on your raft you can have access to all items in this inventory in your crafting menu.
That is all that this mod does ^_^

**Comment by Azzmurr** [comment]
in case of any questions, ping me on this ticket, otherwise, I will close this ticket in a month. Have a good day and play safely
